const PRODUCTS = [
  {"brand":"ABARTH","family":"595","category":"Sécurité","name":"ABARTH 595 BLACK","ref":"CHAB01BK-XX","sizes":"36-48","price_ht":"80,50 €","price_ttc":"","image":"SECURITE/ABARTH-595-CHAB01BK.jpg"},
  {"brand":"ABARTH","family":"595","category":"Sécurité","name":"ABARTH 595 BLACK/RED","ref":"CHAB01BKRD-XX","sizes":"36-48","price_ht":"80,50 €","price_ttc":"","image":"SECURITE/ABARTH-595-CHAB01BKRD.jpg"},
  {"brand":"ABARTH","family":"595","category":"Sécurité","name":"ABARTH 595 CHALLENGE","ref":"CHAB01CH-XX","sizes":"36-50","price_ht":"83,30 €","price_ttc":"","image":"SECURITE/ABARTH-595-CHAB0001CH.jpg"},
  {"brand":"ABARTH","family":"595","category":"Sécurité","name":"ABARTH 595 GREY","ref":"CHAB01GR-XX","sizes":"36-48","price_ht":"80,50 €","price_ttc":"","image":"SECURITE/ABARTH-595-CHAB01GR.jpg"},
  {"brand":"ABARTH","family":"595","category":"Sécurité","name":"ABARTH 595 NAVY","ref":"CHAB01NV-XX","sizes":"36-48","price_ht":"80,50 €","price_ttc":"","image":"SECURITE/ABARTH-595-CHAB01NV.jpg"},
  {"brand":"ABARTH","family":"595","category":"Sécurité","name":"ABARTH 595 WHITE","ref":"CHAB01WH-XX","sizes":"36-48","price_ht":"80,50 €","price_ttc":"","image":"SECURITE/ABARTH-595-CHAB01WH.jpg"},
  {"brand":"ABARTH","family":"ESSEESSE","category":"Sécurité","name":"ABARTH ESSEESSE","ref":"CHAB04BK-XX","sizes":"39-47","price_ht":"67,20 €","price_ttc":"","image":"SECURITE/ABARTH-ESSEESSE-CHAB04BK.jpg"},
  {"brand":"ABARTH","family":"SCORPION","category":"Sécurité","name":"ABARTH SCORPION ALTO","ref":"CHAB07ALBK-XX","sizes":"39-47","price_ht":"97,30 €","price_ttc":"","image":"SECURITE/ABARTH-SCORPION-CHAB07ALBK.jpg"},
  {"brand":"ABARTH","family":"SCORPION","category":"Sécurité","name":"ABARTH SCORPION BASSO","ref":"CHAB07BABK-XX","sizes":"39-47","price_ht":"90,30 €","price_ttc":"","image":"SECURITE/ABARTH-SCORPION-CHAB07BABK.jpg"},
  {"brand":"ABARTH","family":"THUNDER","category":"Sécurité","name":"ABARTH THUNDER","ref":"CHAB08TH","sizes":"39-48","price_ht":"90,30 €","price_ttc":"","image":"SECURITE/ABARTH-THUNDER-CHAB08TH.jpg"},
  {"brand":"ABARTH","family":"TRUCK","category":"Sécurité","name":"ABARTH TRUCK","ref":"CHAB06PLUS-XX","sizes":"39-47","price_ht":"62,30 €","price_ttc":"","image":"SECURITE/ABARTH-TRUCK-CHAB06PLUS.jpg"},
  {"brand":"ABARTH","family":"ZEROCENTO","category":"Sécurité","name":"ABARTH ZEROCENTO BASSO S3","ref":"CHAB03BA-XX","sizes":"39-47","price_ht":"55,30 €","price_ttc":"","image":"SECURITE/ABARTH-ZEROCENTO-CHAB03BA.jpg"},
  {"brand":"ABARTH","family":"ZEROCENTO","category":"Sécurité","name":"ABARTH PARTENZA ESD S3","ref":"CHAB03PA-XX","sizes":"39-47","price_ht":"62,30 €","price_ttc":"","image":"SECURITE/ABARTH-ZEROCENTO-CHAB03PA.jpg"},
  {"brand":"ABARTH","family":"ZEROCENTO","category":"Sécurité","name":"ABARTH ZEROCENTO X-TREM S3","ref":"CHAB03XT-XX","sizes":"39-47","price_ht":"76,30 €","price_ttc":"","image":"SECURITE/ABARTH-ZEROCENTO-CHAB03XT.jpg"},
  {"brand":"DUNLOP","family":"FIRST ONE ADV-EVO","category":"Sécurité","name":"DUNLOP FIRST ONE ADV-EVO LOW S3","ref":"CHDL0201050","sizes":"36-47","price_ht":"62,30 €","price_ttc":"","image":"SECURITE/DUNLOP-FIRST ONE ADV-EVO LOW-CHDL0201050.jpg"},
  {"brand":"DUNLOP","family":"FIRST ONE ADV-EVO","category":"Sécurité","name":"DUNLOP FIRST ONE ADV-EVO TITAN","ref":"CHDL0202008","sizes":"39-47","price_ht":"76,30 €","price_ttc":"","image":"SECURITE/DUNLOP-FIRST ONE ADV-EVO TITAN-CHDL0202008.jpg"},
  {"brand":"DUNLOP","family":"SWORD LINE","category":"Sécurité","name":"DUNLOP SWORD LINE BLUE ESD","ref":"CHDL0201047","sizes":"36-47","price_ht":"83,30 €","price_ttc":"","image":"SECURITE/DUNLOP-SWORD LINE-CHDL0201047.jpg"},
  {"brand":"ABARTH","family":"COMPETIZIONE","category":"Travail","name":"ABARTH COMPETIZIONE GREY","ref":"CHAB02GR","sizes":"36-48","price_ht":"55,30 €","price_ttc":"","image":"TRAVAIL/ABARTH-COMPETIZIONE-CHAB02GR.jpg"},
  {"brand":"ABARTH","family":"COMPETIZIONE","category":"Travail","name":"ABARTH COMPETIZIONE NAVY","ref":"CHAB02NV","sizes":"36-48","price_ht":"55,30 €","price_ttc":"","image":"TRAVAIL/ABARTH-COMPETIZIONE-CHAB02NV.jpg"},
  {"brand":"ABARTH","family":"COMPETIZIONE","category":"Travail","name":"ABARTH COMPETIZIONE WHITE","ref":"CHAB02WH","sizes":"36-48","price_ht":"55,30 €","price_ttc":"","image":"TRAVAIL/ABARTH-COMPETIZIONE-CHAB02WH.jpg"},
  {"brand":"DUNLOP","family":"O2 CARBON","category":"Travail","name":"DUNLOP O2 CARBON","ref":"CHDL0203004","sizes":"36-48","price_ht":"55,30 €","price_ttc":"","image":"TRAVAIL/DUNLOP-O2 CARBON-CHDL0203004.jpg"}
];
